name: Sync Fork

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  # sync:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: tgymnich/fork-sync@v2.0.10
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         head: master
  #         base: master
  #         merge_method: merge
  #         auto_merge: true

  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head: master
          base: master
          merge_method: merge
          auto_merge: true

      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules recursively
        run: |
          git submodule update --init --recursive --remote

      - name: Commit updated submodules if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "chore: update submodules"
            git push
          else
            echo "No submodule updates"
          fi
