name: Sync Fork

on:
  schedule:
    - cron: "0 0 1 * *" # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v2.0.10
